### ISSUE TITLE
Safari: fix error on page load related to IP location

### ISSUE THREAD

**Issue by nickoneill** [5calls/react-dev#17]
Here's the error I get when loading the page:

`fetchLocationByIP error: undefined – "InvalidAccessError"`

**Comment by schraj** [comment]
The location process/widget has a number of things that need to be worked out.  I would see this area as a somewhat more difficult place for someone to start out working on.

**Comment by nickoneill** [comment]
Fair enough!

**Comment by cdoremus** [comment]
This will probably be fixed when issue #10 is implemented.

**Comment by nickoneill** [comment]
This is fixed
