### ISSUE TITLE
Add/import user stats

### ISSUE THREAD

**Issue by nickoneill** [5calls/react-dev#18]
Currently user stats are stored in localstorage on the browser. Hopefully we can read and use these as normal and don't have to do an import procedure.

Also, make sure user stats are amended whenever a user marks an outcome button.

**Comment by schraj** [comment]
we have "redux-persist" persisting/rehydrating redux state from local storage currently.  It interacts well with the redux store and persists/reloads stuff automatically.  We'll need to see if we can adjust the local storage keys that it reads/writes to if we wanted to have it continue to use the key that is currently being used for the user stats.

It wouldn't be a difficult thing to just have the app look for this particular local storage key(the key the choo app uses currently) and if it exists, grab that data and put it into the redux store of the new app(where it would then be persisted in the normal redux way) and then delete the existing local storage key.  Is this what you mean by "Import"? We could do that with existing location data(from choo app) too.

I'll look into redux-persist and see what kind of control we would have over the naming/formatting of the local storage keys it uses/looks for.

**Comment by nickoneill** [comment]
Yep, that's the kind of import I'm talking about. Sounds straightforward though, so if it's easier to pull it if it exists once and then hand it off to redux-persist for future sessions, that's fine. It sounded harder when I was thinking of it earlier.

**Comment by nickoneill** [comment]
Added by @schraj in #38
