### ISSUE TITLE
Add support for issue links

### ISSUE THREAD

**Issue by cdoremus** [5calls/react-dev#34]
The 5 calls API sends back `link` and `linkTitle` data values for each issue. When these values are undefined, they should be displayed below the script. See `script.js` and `issueLink.js` in the Choo repository for details. Also, according to `call.js` in the Choo repository, when an issues link data exists, a contact should not be displayed.

**Comment by nickoneill** [comment]
Reference implementation from previous choo app: https://github.com/5calls/5calls/blob/master/static/js/components/issuesLink.js

**Comment by akarmstrong** [comment]
Gonna attempt this issue!

**Comment by nickoneill** [comment]
This is in #50

**Comment by cdoremus** [comment]
PR #50 has been merged into master
