### ISSUE TITLE
Location gets stuck if page is reloaded when entering location

### ISSUE THREAD

**Issue by nickoneill** [5calls/react-dev#35]
1. A location is set
2. Click the location to change your location
3. While the field is still open (don't hit the "go" button yet), reload the page
4. Location says "getting location" forever and never gets a location

Expected: location should be not set and fetched automatically on refresh

**Comment by cdoremus** [comment]
@nickoneill I could not replicate this bug in Chrome or Firefox on Ubuntu Linux.

**Comment by nickoneill** [comment]
Can't repro anymore, and #51 prevents us from getting into this state
