### ISSUE TITLE
Implement a Local Storage service and use it to persist state

### ISSUE THREAD

**Issue by cdoremus** [5calls/react-dev#4]
In order to be able to restore application state after a page refresh or a invocation of a URL with an issue id, we need to persist state in local storage. This will require the implementation of a local storage service.

This work will be done in conjunction with issue #3 as local storage will be needed to implement that issue.

**Comment by cdoremus** [comment]
Jeremy (@schraj) suggested the [redux-persist](https://github.com/rt2zz/redux-persist) library to do local storage and that seems like the best way to go at this time. The library can seamlessly store all or selected parts of state held by redux in local storage.

**Comment by schraj** [comment]
When you configure it, in the `persistStore()` call in the `redux/store.ts` file, just add the key for the redux store that you want to persist to the "whitelist".

"whitelist" tells the redux-persist middleware which reducer keys(parts of the redux store)
we want to persist and then grab back and put into the store upon loading the app the next time.
It will write to this localstorage key every time there is a change made to this key in redux.

**Comment by cdoremus** [comment]
It's very cool how `redux-persist` works seamlessly and automatically refreshes state from local storage and pushes state updates to local storage. No need to call `localStorage.getItem()` or `localStorage.setItem()` like we do in the Choo implementation. That's a big win!

**Comment by cdoremus** [comment]
The implementation with `redux-persist` in PR #5 by @schraj provides an elegant implementation of local storage. Right now, the application is configured to save `locationState` to local storage via `redux-persist`. See `redux/store.ts` for more details.
