### ISSUE TITLE
Fix footer layout on mobile

### ISSUE THREAD

**Issue by cdoremus** [5calls/react-dev#56]
Footer links need to wrap on a mobile phone. See attached screenshot from my Android phone (impact and about links are missing):

![screenshot_20170902-230605](https://user-images.githubusercontent.com/942174/30000284-018790c0-9034-11e7-9bc7-ba495fa2f938.png)

**Comment by nickoneill** [comment]
This looks good on the current site, but broken on test. Must be something missing, there haven't been any functional changes here.

**Comment by nickoneill** [comment]
Fixed this in 6861846
