### ISSUE TITLE
Implement server-side rendering

### ISSUE THREAD

**Issue by cdoremus** [5calls/react-dev#57]
In order to support issue links that are sharable on Twitter or Facebook, we need to implement server-side rendering of these links (e.g. https//5calls.org/issue/issue101 where issue101 is the issue id)). It would also be useful to support SSR for other pages too such as the About Page that is linked from the 5 Calls mobile apps.

**Comment by nickoneill** [comment]
More details here: https://github.com/5calls/5calls/issues/346
