### ISSUE TITLE
Implement internationalization (i18n)

### ISSUE THREAD

**Issue by cdoremus** [5calls/react-dev#6]
Implement internationalization (i18n) of UI text values.

i18n key values have been put in code comments of all *.tsx files to aid this task.

**Comment by schraj** [comment]
My thought is implement I18n in react-i18next.  There are basically 2 choices and this link from SO is a decent discussion.

https://stackoverflow.com/questions/43460158/react-intl-vs-react-i18next-for-reactjs-internationalization-i18n

Both seem to have about the same features.  As the SO thread mentions, there is not much activity in the last 3 months on react-intl as the lead guy left yahoo.  There are a lot of open issues and PRs. 

We've used i18next for 5Calls and it worked well and I've used it in another react project, though admittedly without the JSX components that it adds.

**Comment by cdoremus** [comment]
Implementation in PR #27 merged into master
